### ISSUE TITLE
Error on DirChanged event

### ISSUE THREAD

**Issue by humeniuc** [ii14/exrc.vim#4]
Hello

I was trying to install `exrc.vim` plugin in vim and the following error triggers:

```
Error detected while processing DirChanged Autocommands for "*":
E716: Key not present in Dictionary: "scope"
```

In the [line45](https://github.com/ii14/exrc.vim/blob/master/plugin/exrc.vim#L45) `autocmd DirChanged * nested if v:event.scope ==# 'global' | confirm ExrcSource | endif` there is a reference to `v:event.scope` who it is not defined in vim, at least not in my installed versions. 
The error appears on vim 8.2 and vim compiled from source. 
In neovim the error does not appear.

Thank you

**Comment by ii14** [comment]
Please update the plugin and see if that fixes the issue.

**Comment by humeniuc** [comment]
Hello

I updated the plugin and now it works, thank you.

I encountered a different issue:
I keep my project specific configs and scrips in a `.workspace` subdirectory in my project directory. So, my exrc file is `.workspace/.exrc.vim` and in my `vimrc` I have `let g:exrc#names = ['.workspace/.exrc.vim']`. 
The problem is that `exrc#trust()` fails on filename check because only filenames are checked, but no subpaths.

I don't know if you intend to support subpaths. but here is a patch. I am not very familiar with vimscript, so it is very likely that the patch could be written in a better way.

``` diff
diff --git a/autoload/exrc.vim b/autoload/exrc.vim
index 804781e..c0e5242 100644
--- a/autoload/exrc.vim
+++ b/autoload/exrc.vim
@@ -121,16 +121,26 @@ fun! exrc#trust(fname, force) abort
   endif

   " validate filename
-  let tail = fnamemodify(a:fname, ':t')
-  if index(s:names, tail) == -1
+  let full = fnamemodify(a:fname, ':p')
+  let matched_allowed_names = 0
+
+  " check if full filepath ends with an allowed filename/path
+  for name in s:names
+    let name = substitute('/' . name, '\/\/', '/', '') " name with a slash prefix
+    if matchend(full, name) == strlen(full)
+        let matched_allowed_names = 1
+        break
+    endif
+  endfor
+
+  if ! matched_allowed_names
     call s:Error(
       \ 'Invalid filename "%s". Run :ExrcEdit to edit the config or add the filename to g:exrc#names',
-      \ tail)
+      \ a:fname)
     return
   endif

   " add the config file to trusted files
-  let full = fnamemodify(a:fname, ':p')
   let hashes = s:Read()
   if !a:force
     for item in hashes

```

**Comment by ii14** [comment]
Okay, I'll add support for subpaths. Thanks for reporting the issue.
